name: CI Builds

permissions:
  contents: read

on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      branch:
        type: choice
        description: 'Branch to build'
        options: [master, develop]

concurrency: ci_build-${{ github.event.inputs.branch || github.ref_name }}

jobs:
  ci_builds:
    name: "CI Build"
    runs-on: ubuntu-latest
    timeout-minutes: 1380
    strategy:
      fail-fast: false
      matrix:
        keymap: [default, macvim]
        keyboard: ['annepro2/c18']

    container: ghcr.io/qmk/qmk_cli

    steps:
    - name: Disable safe.directory check
      run : git config --global --add safe.directory '*'

    - name: Checkout QMK
      uses: actions/checkout@v4
      with:
        repository: qmk/qmk_firmware
        fetch-depth: 0
        fetch-tags: false
        ref: 'develop'
        submodules: recursive
    - name: Checkout keymap MacVim
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
        path: 'keyboards/annepro2/keymaps/macvim'

    - name: Install dependencies
      run: pip3 install -r requirements.txt

    - name: Run `qmk compile` (keyboard ${{ matrix.keyboard }} keymap ${{ matrix.keymap }})
      run: |
        export NCPUS=$(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || getconf _NPROCESSORS_ONLN 2>/dev/null)
        qmk compile -j $NCPUS -kb ${{ matrix.keyboard }} -km ${{ matrix.keymap }} -e DUMP_CI_METADATA=yes || touch .failed
        # Generate the step summary markdown
        ./util/ci/generate_failure_markdown.sh > $GITHUB_STEP_SUMMARY || true
        # Truncate to a maximum of 1MB to deal with GitHub workflow limit
        truncate --size='<960K' $GITHUB_STEP_SUMMARY || true
        # Exit with failure if the compilation stage failed
        [ ! -f .failed ] || exit 1

    - name: 'Upload artifacts'
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: artifacts-${{ github.event.inputs.branch || github.ref_name }}-${{ matrix.keymap }}
        if-no-files-found: ignore
        path: |
          *.bin
          *.hex
          *.uf2
          .build/failed.*
